### PR TITLE
fix in PCRData class: used min_pcr_tests

### PR DESCRIPTION
**Pull request by Inglezos**
## Related issues
Improvement in PCRData class: used min_pcr_tests and changed default window.

### CODE REVIEW

**Comment by Inglezos** [comment]
@lisphilar do you have any idea why the semaphoreci build failed?

**Comment by lisphilar** [comment]
Thank you for your pull request, but please create and link a issue for this update.

This errors does not related to this pull request... It is due to data downloading of linelist...
I will investigate it...

The error codes is
```Python
covsirphy/cleaning/dataloader.py:171: in jhu
    jhu_data.recovery_period = self.linelist(
covsirphy/cleaning/dataloader.py:252: in linelist
    self._linelist_data = LinelistData(
covsirphy/cleaning/linelist.py:45: in __init__
    self._raw = self._retrieve(filename=filename, verbose=verbose)
covsirphy/cleaning/linelist.py:69: in _retrieve
    df = self.load(self.URL, header=1)
covsirphy/cleaning/cbase.py:68: in load
    return dd.read_csv(urlpath, blocksize=None, **kwargs).compute()
../.local/share/virtualenvs/covid19-sir-kT3BL-HO/lib/python3.8/site-packages/dask/dataframe/io/csv.py:700: in read
    return read_pandas(
../.local/share/virtualenvs/covid19-sir-kT3BL-HO/lib/python3.8/site-packages/dask/dataframe/io/csv.py:579: in read_pandas
    head = reader(BytesIO(b_sample), **kwargs)
../.local/share/virtualenvs/covid19-sir-kT3BL-HO/lib/python3.8/site-packages/pandas/io/parsers.py:688: in read_csv
    return _read(filepath_or_buffer, kwds)
../.local/share/virtualenvs/covid19-sir-kT3BL-HO/lib/python3.8/site-packages/pandas/io/parsers.py:460: in _read
    data = parser.read(nrows)
../.local/share/virtualenvs/covid19-sir-kT3BL-HO/lib/python3.8/site-packages/pandas/io/parsers.py:1198: in read
    ret = self._engine.read(nrows)
../.local/share/virtualenvs/covid19-sir-kT3BL-HO/lib/python3.8/site-packages/pandas/io/parsers.py:2157: in read
    data = self._reader.read(nrows)
pandas/_libs/parsers.pyx:850: in pandas._libs.parsers.TextReader.read
    ???
pandas/_libs/parsers.pyx:933: in pandas._libs.parsers.TextReader._read_rows
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 11, saw 3
```

https://semaphoreci.com/lisphilar/covid19-sir/branches/issue422/builds/4

**Comment by Inglezos** [comment]
What is going on with the build environment? Is this a general issue right? What caused this? I see you have the same problem with your pull request build?

**Comment by lisphilar** [comment]
This is a general issue. I created #442.

**Comment by lisphilar** [comment]
This will be merged after tests passed and minor version 2.13.2 released.

**Comment by lisphilar** [comment]
Please rebase with my default branch.

**Pull request merged**
