### PR TITLE
test693 - min_size=7 in data_handler + use Q1 and mean in scenario.estimate_delay()

### PR DESCRIPTION
**Pull request by Inglezos**
## Related issues
Test pull request for issue #693

## What was changed
Changed min_size to 7 in data_handler (while keeping Pelt-rbf) + used Q1 and mean in scenario.estimate_delay()

@lisphilar
I created this first test pull request. Can you please elaborate on what you meant by extra arguments and keeping same outputs as before? Because these changes affect the previous returned delay value. Do not merge anything yet. You can see the changes I proposed and maybe try them if you have some time. I will have time for coding again today late evening UTC.

### CODE REVIEW

**Comment by lisphilar** [comment]
> Can you please elaborate on what you meant by extra arguments and keeping same outputs as before? Because these changes affect the previous returned delay value. Do not merge anything yet.

I thought the following arguments will be added so that we can get the output with both of the corrent strategy and the new strategy at the same new version after merging this pull request.

- `DataHandler.estimate_delay(min_size=0)`
- `Scenario.estimate_delay(min_size=7, limits=(None, 0.99), represent="mode")`

(When `limits=(0.25, None), represent="Q1")`, outputs will be the new one.)

But, this pull request will not be merged until solving the all problems?

**Comment by lisphilar** [comment]
I updated this pull request directly to
- add argument `min_size=7` and `use_difference=False` to `DataHandler.estimat_delay()`
- when `use_difference=True`, "Confirmed.diff()" will be used as the target
- deprecate `value_range` argument of `Scenario.estimate_delay()`
- add argument `percentile=25` to `Scenario.estimate_delay()` so that we can controll Q1 percentile
- add `**kwargs` to `Scenario.estimate_delay()` so that we can use `use_difference` in this method too

@Inglezos,
Could you try `Scenario.estimate_delay(use_difference=True)` if you have time. In Hugary case, "8 days" will be returned with `len(df) = 21`. (When `use_difference=False`, 14 days with `len(df) = 10`.)
As draft, `use_difference=False` as default.

**Comment by Inglezos** [comment]
@lisphilar Thank you for the changes!
Yes for Hungary I get the same results.
I will push a change with max_days argument set to 30 days (default) that is the maximum delay period. I think that since we are trying to calculate Q1, we don't need values longer than 1 month to be reflected in the `min_size` value for `trend()`.

Actually these are the results for various countries **without** max_days (pass argument `max_days=None`):
image

And **with** max_days:
image

This idea occurred to me because I saw that with the code as it is, the France had a large partial delay value (56 if I remember correctly). Alternatively we could revert the value_range or 0.99 percentile filtering.

**Comment by lisphilar** [comment]
Just for refactoring, argument `min_size=7, max_days=30` was replaced with `limits=(7, 30)` in `Scenario.estimate_delay()`.

**Comment by lisphilar** [comment]
We keep `use_difference=False` argument in `DataHandler.estimate_delay()`?
With my test, we have both of the following two approaches
1. `percentile=25, use_difference=False`
2. `percentile=50, use_difference=True`
an estimated values are somewhat close.

Anyway, we can merge this pull request.

**Comment by Inglezos** [comment]
Yes we can now merge this.
I think we should keep the `use_difference` argument for the moment yes.
Also we have to keep in mind that we will need to use a second `estimate_delay()` for the forecast, as there the return value will probably follow similar but not identical logic, right?

**Comment by lisphilar** [comment]
Thank you for your confirmation and I will merge this pull request.
We keep `use_difference=False` and return to #693 and #668 to discuss arguments of `.estimate_delay()` specified in `.trend()` and `.fit()`.

**Pull request merged**
