### PR TITLE
add: full complement when R >> I when outbreaking

### PR DESCRIPTION
**Pull request by lisphilar**
## Related issues
This is related to #339 

## What was changed
When the number of recovered cases is too large when outbreaking, full complement on recovered data will be done.

### CODE REVIEW

**Review by Inglezos — APPROVED** [review]
I don't know if the condition `sel_2 = subset_df[self.C].diff().diff() > 0` is definitive for every case, but if something comes up later we can rework this. I think this implementation is enough for now.

**Comment by lisphilar** [comment]
Dear @Inglezos ,
Is your concern that `sel_2 = subset_df[self.C].diff().diff() > 0` is week condition for subsetting? Is `subset_df[self.C].diff().diff().rolling(window=14).mean()` effective?

**Comment by Inglezos** [comment]
> Dear @Inglezos ,
> Is your concern that `sel_2 = subset_df[self.C].diff().diff() > 0` is week condition for subsetting? Is `subset_df[self.C].diff().diff().rolling(window=14).mean()` effective?

Yes it could be proven to be kinda weak condition. For example, if the pandemic is outbreaking, then it is almost diminished for some months and then again outbreaks (as happened in some countries in the summer), then this condition would indicate full compliment and would ignore the correct actual recovered records altogether.

Yes the rolling window is more safe and more effective!

**Comment by lisphilar** [comment]
Thank you for your reply.
I added `.rolling(14).mean()`. I will merge this pull request after completion of tests.

Before releasing the next stable version, it will be necessary to check the list of countries where complement performed.

**Pull request merged**
